### ISSUE TITLE
Compatible with 1.9?

### ISSUE THREAD

**Issue by jean** [Lombiq/Pretty-Good-Bootstrap-Base-Theme-Sample#1]
In https://github.com/Lombiq/Pretty-Good-Bootstrap-Base-Theme-Sample/blame/master/Readme.md#L18 I read that the theme targets `1.x` branch, **"to-be `1.8`"**, but we're already at `1.9`, so the release mentioned can probably be updated or omitted.

**Comment by Piedone** [comment]
You're right, fixed the Readme now. It's actually upgraded for 1.10.1 too. Thanks for noticing.
